server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-origins: "*"
            allowed-headers: "*"
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: PLAYLIST-SERVICE
          uri: lb://PLAYLIST-SERVICE
          predicates:
            - Path=/api/v1/playlists/**


eureka:
  client:
    service-url:
      defaultZone: http://192.168.80.4:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: psm

