#spring.application.name=jpa
#spring.datasource.url=jdbc:mysql://localhost:3306/music_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#spring.datasource.password=1234
#spring.datasource.username=root


server:
  port: 9000
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/music_test2?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.80.4:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: psm


token:
  secret: vsddsaed213214rfsdagsd4983fwe43r234981742*1wdsfa56f1ads32v1xc2zvcxzcxzvgweaaa
  expiration: 60000


