#  application.yaml#spring.application.name=jpa
#spring.datasource.url=jdbc:mysql://localhost:3306/music_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#spring.datasource.password=1234
#spring.datasource.username=root


eureka:
  client:
    enabled: false
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:test
    password:
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

token:
  secret: vsdab1232fkewbquriebp12315555555aa
  expiration: 60000


