#spring.application.name=jpa
#spring.datasource.url=jdbc:mysql://localhost:3306/music_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#spring.datasource.password=1234
#spring.datasource.username=root



spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://192.168.80.4:3306/music_test2?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: psm


token:
  secret: vsdab1232fkewbquriebp12315555555aa
  expiration: 60000


