#spring.application.name=jpa
#spring.datasource.url=jdbc:mysql://localhost:3306/music_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#spring.datasource.password=1234
#spring.datasource.username=root
server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_test3?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: playlist-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: psm

token:
  secret: vsdab1232fkewbquriebp12315555555aa
  expiration: 600000